# Generated by Django 3.1.7 on 2021-03-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_impotado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ncm',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_produto',
            field=models.CharField(default=None, max_length=8, verbose_name='codigo'),
        ),
    ]
